# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/WorkSpace/constr.xdc

# Block Designs: bd/design_rx_reg/design_rx_reg.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rx_reg || ORIG_REF_NAME==design_rx_reg} -quiet] -quiet

# IP: bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rx_reg_clk_wiz_0_0 || ORIG_REF_NAME==design_rx_reg_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_rx_reg/ip/design_rx_reg_RX_register_0_0/design_rx_reg_RX_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rx_reg_RX_register_0_0 || ORIG_REF_NAME==design_rx_reg_RX_register_0_0} -quiet] -quiet

# IP: bd/design_rx_reg/ip/design_rx_reg_ila_0_0/design_rx_reg_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_rx_reg_ila_0_0 || ORIG_REF_NAME==design_rx_reg_ila_0_0} -quiet] -quiet

# XDC: bd/design_rx_reg/design_rx_reg_ooc.xdc
