# Clock related constraints
create_clock -period 10.000 -name clk_100MHz -waveform {0.000 5.000} [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN W5 [get_ports clk_100MHz]




set_property IOSTANDARD LVCMOS33 [get_ports { rx_in }]
set_property PACKAGE_PIN G2 [get_ports { rx_in }]






#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw0_in8[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sw1_in8[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led0_out8[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led1_out8[7]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sevenseg[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SEVENseg_AN[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SEVENseg_AN[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SEVENseg_AN[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {SEVENseg_AN[3]}]
##set_property IOSTANDARD LVCMOS33 [get_ports reset]

#set_property PACKAGE_PIN V17 [get_ports {sw0_in8[0]}]
#set_property PACKAGE_PIN V16 [get_ports { sw0_in8[1] }]
#set_property PACKAGE_PIN W16 [get_ports {sw0_in8[2]}]
#set_property PACKAGE_PIN W17 [get_ports {sw0_in8[3]}]
#set_property PACKAGE_PIN W15 [get_ports {sw0_in8[4]}]
#set_property PACKAGE_PIN V15 [get_ports {sw0_in8[5]}]
#set_property PACKAGE_PIN W14 [get_ports { sw0_in8[6] }]
#set_property PACKAGE_PIN W13 [get_ports {sw0_in8[7]}]
#set_property PACKAGE_PIN V2  [get_ports { sw1_in8[0] }]
#set_property PACKAGE_PIN T3  [get_ports { sw1_in8[1] }]
#set_property PACKAGE_PIN T2  [get_ports { sw1_in8[2] }]
#set_property PACKAGE_PIN R3  [get_ports { sw1_in8[3] }]
#set_property PACKAGE_PIN W2  [get_ports { sw1_in8[4] }]
#set_property PACKAGE_PIN U1  [get_ports { sw1_in8[5] }]
#set_property PACKAGE_PIN T1  [get_ports { sw1_in8[6] }]
#set_property PACKAGE_PIN R2  [get_ports { sw1_in8[7] }]

set_property PACKAGE_PIN U16 [get_ports {led0_out8[0]}]
set_property PACKAGE_PIN E19 [get_ports {led0_out8[1]}]
set_property PACKAGE_PIN U19 [get_ports {led0_out8[2]}]
set_property PACKAGE_PIN V19 [get_ports {led0_out8[3]}]
set_property PACKAGE_PIN W18 [get_ports {led0_out8[4]}]
set_property PACKAGE_PIN U15 [get_ports {led0_out8[5]}]
set_property PACKAGE_PIN U14 [get_ports {led0_out8[6]}]
set_property PACKAGE_PIN V14 [get_ports {led0_out8[7]}]
#set_property PACKAGE_PIN V13 [get_ports {led1_out8[0] }]
#set_property PACKAGE_PIN V3  [get_ports { led1_out8[1] }]
#set_property PACKAGE_PIN W3  [get_ports { led1_out8[2] }]
#set_property PACKAGE_PIN U3  [get_ports { led1_out8[3] }] 
#set_property PACKAGE_PIN P3  [get_ports { led1_out8[4] }]
#set_property PACKAGE_PIN N3  [get_ports { led1_out8[5] }]
#set_property PACKAGE_PIN P1  [get_ports { led1_out8[6] }]
#set_property PACKAGE_PIN L1  [get_ports { led1_out8[7] }]

#set_property PACKAGE_PIN W7 [get_ports {sevenseg[0]}]
#set_property PACKAGE_PIN W6 [get_ports {sevenseg[1]}]
#set_property PACKAGE_PIN U8 [get_ports {sevenseg[2]}]
#set_property PACKAGE_PIN V8 [get_ports {sevenseg[3]}]
#set_property PACKAGE_PIN U5 [get_ports {sevenseg[4]}]
#set_property PACKAGE_PIN V5 [get_ports {sevenseg[5]}]
#set_property PACKAGE_PIN U7 [get_ports {sevenseg[6]}]
#set_property PACKAGE_PIN V7 [get_ports {sevenseg[7]}]
#set_property PACKAGE_PIN W4  [get_ports {SEVENseg_AN[3]} ] 
#set_property PACKAGE_PIN V4  [get_ports {SEVENseg_AN[2]} ] 
#set_property PACKAGE_PIN U4  [get_ports {SEVENseg_AN[1]} ] 
#set_property PACKAGE_PIN U2  [get_ports {SEVENseg_AN[0]} ] 
#set_property PACKAGE_PIN T18 [get_ports reset]
