# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0.xci
# IP: The module: 'design_rx_reg_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0.xci
# IP: The module: 'design_rx_reg_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/arify/WorkSpace/Basys3_T2209/project_test/project_test.srcs/sources_1/bd/design_rx_reg/ip/design_rx_reg_clk_wiz_0_0/design_rx_reg_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_rx_reg_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
